language: C++

dist: xenial

if: type = push

install:
    - sudo apt-get install gcc-aarch64-linux-gnu
    
script:
    - sudo apt-get install python3.5
  
after_success:
    - sudo apt-get install pylint
deploy:
  - provider: cloudcontrol
    email: "YOUR CLOUDCONTROL EMAIL"
    password: "YOUR CLOUDCONTROL PASSWORD"
    deployment: "APP_NAME/DEP_NAME"
  - provider: heroku
    api_key: "YOUR HEROKU API KEY"
